#!/usr/bin/env bash                                                                                                                                                            
ssh -i  ~/.ssh/schoo  ubuntu@100.26.142.236
